name: Build

on:
  push:
    branches: [ 0.4.9 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload meteor
        uses: actions/upload-artifact@v3
        with:
          name: meteor-1.18.2-0.4.9
          path: build/libs
